import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` antialiased`}
      >
<<<<<<< Updated upstream
        <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
=======
<<<<<<< Updated upstream
        {children}
=======
        <ThemeProvider
                          attribute="class"
                          defaultTheme="system"
                          enableSystem
                          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
>>>>>>> Stashed changes
>>>>>>> Stashed changes
      </body>
    </html>
  );
}
